USE [master]
GO

/****** Object:  Database [TestBase]    Script Date: 30.07.2020 16:57:38 ******/
CREATE DATABASE [TestBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestBase', FILENAME = N'F:\SQL Server\NewServer2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestBase_log', FILENAME = N'F:\SQL Server\NewServer2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestBase_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestBase] SET RECOVERY FULL 
GO

ALTER DATABASE [TestBase] SET  MULTI_USER 
GO

ALTER DATABASE [TestBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestBase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestBase] SET  READ_WRITE 
GO

